{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyDriver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IHorizontalTextCarouselDriver","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IHorizontalTextCarouselDriver","text":"IHorizontalTextCarouselDriver"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatroomuikit\/roomservice\/notifydriver"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/notifyDriver","interfaceLanguage":"swift"},"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel"},{"type":"text","text":" UI driver"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyDriver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IHorizontalTextCarouselDriver","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IHorizontalTextCarouselDriver"},{"kind":"text","text":"?"}],"title":"notifyDriver","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChatroomUIKit11RoomServiceC12notifyDriverAA023IHorizontalTextCarouselF0_pSgvp","modules":[{"name":"ChatroomUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService"]]},"references":{"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService":{"role":"symbol","title":"RoomService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomService"}],"abstract":[{"type":"text","text":"Chat room hub service transfer class in chat room UIKit."}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoomService"}],"url":"\/documentation\/chatroomuikit\/roomservice"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/HorizontalTextCarousel":{"role":"symbol","title":"HorizontalTextCarousel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HorizontalTextCarousel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HorizontalTextCarousel"}],"url":"\/documentation\/chatroomuikit\/horizontaltextcarousel"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit":{"role":"collection","title":"ChatroomUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/RoomService/notifyDriver":{"role":"symbol","title":"notifyDriver","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyDriver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IHorizontalTextCarouselDriver","preciseIdentifier":"c:@M@ChatroomUIKit@objc(pl)IHorizontalTextCarouselDriver"},{"kind":"text","text":"?"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/HorizontalTextCarousel"},{"type":"text","text":" UI driver"}],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/RoomService\/notifyDriver","kind":"symbol","type":"topic","url":"\/documentation\/chatroomuikit\/roomservice\/notifydriver"},"doc://org.cocoapods.ChatroomUIKit/documentation/ChatroomUIKit/IHorizontalTextCarouselDriver":{"role":"symbol","title":"IHorizontalTextCarouselDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IHorizontalTextCarouselDriver"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChatroomUIKit\/documentation\/ChatroomUIKit\/IHorizontalTextCarouselDriver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IHorizontalTextCarouselDriver"}],"url":"\/documentation\/chatroomuikit\/ihorizontaltextcarouseldriver"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/title","value":"RoomService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1RoomService\/fragments","value":[{"kind":"identifier","text":"RoomService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/title","value":"HorizontalTextCarousel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1HorizontalTextCarousel\/fragments","value":[{"kind":"identifier","text":"HorizontalTextCarousel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IHorizontalTextCarouselDriver\/title","value":"IHorizontalTextCarouselDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChatroomUIKit~1documentation~1ChatroomUIKit~1IHorizontalTextCarouselDriver\/fragments","value":[{"kind":"identifier","text":"IHorizontalTextCarouselDriver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}